### ISSUE TITLE
docker-compose and vnc settings

### ISSUE THREAD

**Issue by arumals** [elgalu/docker-selenium#119]
#### Docker-Compose

Hi, probably this is a very simple question for some of you, but I cant find the information inside the documentation.

I can access the grid using the vnc to visualize the chrome browser execution. But if I use docker-compose I don't really understand where the vnc configuration must be set and how to access each of the individual containers.

I tried to look in multiple posts but unfortunately there isn't I couldn't find anything.

Thanks

**Comment by elgalu** [comment]
Hi, if you start each container manually, instead of using docker-compose, you would probably export each VNC port to different numbers like:

```sh
docker run -d --name=grid1 --p 5900:25900 -v /dev/shm:/dev/shm elgalu/selenium
docker run -d --name=grid2 --p 5901:25900 -v /dev/shm:/dev/shm elgalu/selenium
docker run -d --name=grid3 --p 5902:25900 -v /dev/shm:/dev/shm elgalu/selenium
```

Then you would VNC to ports `5900`, `5901` and `5902` as shown in that example.

With docker-compose is the same, it only changes were you set that port mapping, instead of doing it in the command line you do it in a config file, see for example:

```yaml
services:
  grid1:
    image: elgalu/selenium
    ports:
      - 5900:25900
```

**Comment by elgalu** [comment]
Does that help?

**Comment by elgalu** [comment]
No response so closing...
