### ISSUE TITLE
Question: Video Recording with Concurrent Tests

### ISSUE THREAD

**Issue by seangerhardt-wf** [elgalu/docker-selenium#134]
In the README, it states

>  The drawback is that all tests will run on the same desktop meaning the video recording will only capture the browser in the foreground but it's in the roadmap to make all this transparent, see issues #78 and #77.

It appears these issues are now closed and they point to https://github.com/zalando-incubator/zalenium.

My question is, **how is video recording concurrent tests currently implemented in _this_ repo**, and should the documentation be updated now that those issues are closed?

Thanks!
Sean

**Comment by elgalu** [comment]
The drawback / downside is still valid because it refers to using "-e MAX_INSTANCES=20 -e MAX_SESSIONS=20" which causes all the sessions to start on the same desktop.

I would update that README section adding that [Zalenium](https://github.com/zalando-incubator/zalenium) is out and covers this use case much better.

**Comment by elgalu** [comment]
For Video Recording with Concurrent Tests we are now supporting [Zalenium](https://github.com/zalando/zalenium) which internally uses this project but is now Zalenium that handles the parallelization and management of docker-selenium containers.
