### ISSUE TITLE
Video splits incorrectly

### ISSUE THREAD

**Issue by christopheg** [elgalu/docker-selenium#143]
Dear,

Since release 3.1.0-p2, there seems to be something wrong with the video recording. Our tests run for about an hour. In previous versions, this resulted in various different mp4 files in /videos, all containing 5 minutes of the test.
Filenames looked like this:
vid_chrome_25550_firefox_25551.mp4
vid_chrome_25550_firefox_25551-001.mp4
vid_chrome_25550_firefox_25551-002.mp4
vid_chrome_25550_firefox_25551-003.mp4

Since release 3.1.0-p2, only 1 file is created:
vid_chrome_25550_firefox_25551.mp4
This file contains 15 minutes of our test. So it looks that:
- The default behavior of splitting after 5 minutes has been changed to 15 minutes.
- The documentation in /docs/videos.md mentions a chunk interval of 10 minutes
- Only the first part is actually saved

Our temporary solution is to set the VIDEO_CHUNK_SECS to an unusual "02:00:00". However, would it be possible to bring back this split feature?

Thanks,

**Comment by elgalu** [comment]
Hi @christopheg thanks for reporting it, I'm really sorry about this breaking change.

I had to remove the splitting functionality because it was incompatible with [Zalenium](https://github.com/zalando/zalenium) which is the project @diemol and I are focusing our energy, Zalenium will be presented in April at http://seleniumconf.com/

Having that clarified, I'm glad you found the `VIDEO_CHUNK_SECS` setting, you can send me a PR with the new 2hs (or more) default as I think it makes more sense since I don't split the video anymore.

You can go with that setting or instead of using `latest` tag, use the version that still had the splitting, any vesion <= [3.1.0-p0](https://github.com/elgalu/docker-selenium/releases/tag/3.1.0-p0)

**Comment by christopheg** [comment]
Pull request created. I completely removed the setting. I hope you agree with me that by simply increasing the default value of it leads to unexpected behavior.

**Comment by elgalu** [comment]
Released: https://github.com/elgalu/docker-selenium/releases/tag/3.1.0-p3

Thanks for your contribution @christopheg

**Comment by elgalu** [comment]
With latest releases videos are not spitted anymore.
