### ISSUE TITLE
Sendkeys speed degression

### ISSUE THREAD

**Issue by christopheg** [elgalu/docker-selenium#154]
There is e serious decrease in performance for 'sendKeys' after version 3.1.0-p3.
To demonstrate this, I created an easy Selenium scene: 
- open Chrome
- open test page that contains 1 textarea
- fill in 2 paragraphs of Lorum Ipsum in textarea (via sendKeys)

With version 3.1.0-p3, the tests takes 7.45 seconds.
With the latest version (3.3.1-p9), the test takes 24.91 seconds.

the docker startup command we use is:
`docker run -d --name=selenium -p 4444:24444 -p 5900:25900 -e TZ="Europe/Brussels" -e VNC_PASSWORD=knx -e MAX_INSTANCES=20 -e MAX_SESSIONS=20 -e SCREEN_WIDTH=1280 -e SCREEN_HEIGHT=1024 -v /dev/shm:/dev/shm elgalu/selenium`

**Comment by elgalu** [comment]
Hi @christopheg I quickly tried but was unable to recreate by using a Protractor project that does sendKeys, I get very similar test time results with both versions 3.1.0 and 3.3.1.

1. Can you try with version `3.3.1-p8` instead of `3.3.1-p9` ?

2. Is this simple test: Chrome => sendKeys("Lorum Ipsum") takes 7.45 seconds? sounds like too much already?

3. It looks I will need more info like binding versions, but even better would be to have a complete scenario that recreates the issue along with all the dependencies required, e.g. a Dockerfile with a dummy localhost page with the text area, the selenium bindings, java/whatever versions, etc..

**Comment by christopheg** [comment]
Actually these are the timings I get from PHPUnit. We use the Facebook webdriver in PHPUnit to connect to the selenium docker.
I will prepare a standalone example. 
Thanks already!

**Comment by christopheg** [comment]
Hi,
I have switched the version a couple of time and now I am unable to reproduce this. The problem could have been related to our environment. You can close this issue. If ever I would be able to provide you with more information I'll open a new issue.
Sorry for the inconvenience!
