### ISSUE TITLE
Unable to build images for older versions of Chrome 

### ISSUE THREAD

**Issue by remeltucker** [elgalu/docker-selenium#302]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
Mac OS
#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`
3.141.59-p2
- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [ ] I have latest version of docker and I will specify here the output of `docker --version`

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [ ] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

Question -Is there a way to build the image for older versions of chrome?
I am currently having the dockerfile for 3.141.59-p2 and tried rebuilding after adding ENV params. It fails since current version of chrome is higher than the one specified in the dockerfile.
Does updating ARG EXPECTED_CHROME_VERSION and commenting out the line where it compares latest version vs expected version help?

**Comment by diemol** [comment]
@remeltucker some work is needed on your side because Google does not keep a repository with all the versions available. So you need to modify the Dockerfile and use a Google installer for the version you need. Now, for that you can search and find an installed around the internet or you could check the releases https://github.com/elgalu/docker-selenium/releases and see that the Chrome deb package is kept there, so you could also use that one.

**Comment by remeltucker** [comment]
Thanks @diemol .Appreciate your response.
